const sections = [
  {
    title: `Platz 1 Ranking bei Google für den Suchbegriff „Familienhotel Schwabing“`,
    text: `Seit mehreren Jahren optimieren wir die Website des Stadthotels „Schwabinger Wahrheit“ aus München mit dem Ziel, das Hotel bei Google ganz oben zu positionieren, um mehr Hotelgäste zu gewinnen. Das Hotel rankt durch die Optimierungen für viele wichtige Suchbegriffe auf Platz 1 bei Google.`,
    googleResults: `Platz 1 bei Google für „Familienhotel Schwabing“`,
    preAIresults: "KI: ",
    aiResults: `Platz 1 in der KI-Antwort von ChatGPT für „Bestes Familienhotel in Schwabing“`,
    company: `Schwabinger Wahrheit - Hotel in München`,
  },
  {
    title: `Platz 1 Ranking bei Google für den Suchbegriff „Immobilienberatung für Investoren“`,
    text: `Der Ergoneon Management GmbH aus München helfen wir seit mehreren Jahren dabei, bei Google und ChatGPT sichtbarer zu werden. Ziel ist es, über starke Google-Positionierungen mehr Investoren zu gewinnen. Für das wettbewerbsintensive Keyword „Immobilienberatung München“ rankt Ergoneon auf Platz 2 bei Google.`,
    googleResults: `Platz 2 bei Google für „Immobilienberatung München“`,
    preAIresults: "Google: ",
    aiResults: `Platz 1 bei Google für „Immobilienberatung für Investoren“`,
    company: `Ergoneon Management GmbH`,
  },
  {
    title: `Platz 1 Ranking bei Google für das Keyword „Immobilienbetreuung Griechenland“`,
    text: `Um mehr Immobilienkäufer aus Deutschland zu erreichen, haben wir die Website greco-immobilien.com (Spezialist für Immobilien im Süden von Griechenland) so optimiert, dass sie eine hohe Google Sichtbarkeit hat. Für das Keyword „Immobilienbetreuung Griechenland“ rankt die Seite auf Platz 1 bei Google.`,
    googleResults: `Platz 1 bei Google für „Immobilienbetreuung Griechenland“`,
    preAIresults: "KI: ",
    aiResults: `Platz 2 in der ChatGPT-Antwort für „Deutscher Makler für Immobilienkauf in Griechenland“`,
    company: `greco-immobilien.com`,
  },
  {
    title: `Platz 1 Ranking bei Google für das Keyword „Eventagentur Bad Tölz“`,
    text: `Für die Werbe- und Eventagentur Crossing Mind aus Bad Tölz haben wir geschäftsrelevante Unterseiten gebaut, um mit der Website mehr Firmenkunden erreichen zu können und mehr Neukundenumsatz zu machen. Für das Keyword „Eventagentur Bad Tölz“ rankt die Firma auf Platz 1 bei Google.`,
    googleResults: `Platz 1 bei Google für „Eventagentur Bad Tölz“`,
    preAIresults: "KI: ",
    aiResults: `Platz 1 in der ChatGPT-Antwort für „Eventagentur für Weihnachtsfeier in Bad Tölz“`,
    company: `Crossing Mind aus Bad Tölz`,
  },
  {
    title: `Platz 1 Ranking bei Google für „Statiker Wolfratshausen“`,
    text: `Die Eisenhut-Statik GmbH realisiert Bauprojekte in Wolfratshausen, München und dem ganzen Oberland. Wir haben die Website so optimiert, dass sie bei Google für wichtige Suchbegriffe oben gefunden werden kann. Die Firma gewinnt nun laufend neue Kunden über die Homepage. Für „Statiker Wolfratshausen“ rankt die Seite auf Platz 1 bei Google.`,
    googleResults: `Platz 1 bei Google für „Statiker Wolfratshausen“`,
    preAIresults: "KI: ",
    aiResults: `Platz 1 in der KI-Antwort von ChatGPT für „Bester Statiker in Wolfratshausen“`,
    company: `Eisenhut-Statik GmbH`,
  },
  {
    title: `Platz 1 Ranking bei Google für „EDV Firma Geretsried“`,
    text: `Mit unserer SEO-Arbeit haben wir die IT-Firma infoteQ aus Geretsried-Gelting bei Google für „EDV Firma Geretsried“ auf Platz 1 katapultiert. Der IT-Dienstleister bekommt nun immer mehr Anfragen über die Website und kann die Seite als Vertriebskanal nutzen.`,
    googleResults: `Platz 1 bei Google für „EDV Firma Geretsried“`,
    preAIresults: "KI: ",
    aiResults: `Platz 1 in der KI-Antwort von ChatGPT für „EDV Firma Geretsried“`,
    company: `nfoteQ EDV Service GmbH`,
  },
  {
    title: `Platz 1 Ranking bei Google für „Unternehmensberater Wolfratshausen“`,
    text: `Mit unseren Google-Optimierungen für die Beratungsfirma „Fröhlich und Partner“ haben wir es geschafft, die Website auf Platz 1 bei Google festzusetzen. Für das Keyword „Unternehmensberater Wolfratshausen“ rankt die Seite auf Platz 1 bei Google. Um die Präsenz zusätzlich zu erhöhen, schalten wir Google Ads für wichtige Suchbegriffe.`,
    googleResults: `Platz 1 bei Google für „Unternehmensberater Wolfratshausen“`,
    preAIresults: "KI: ",
    aiResults: `Platz 1 in der KI-Antwort von ChatGPT für „Unternehmensberater Wolfratshausen“`,
    company: `Unternehmensberater Wilfried Fröhlich`,
  },
  {
    title: `Platz 3 Ranking bei Google für „Erodiertechnik“`,
    text: `Der Firma „SR Erodiertechnik“ aus Ergertshausen helfen wir dabei, die Sichtbarkeit bei Google und im Internet zu steigern, um mehr Neukunden gewinnen zu können. Für das Keyword „Erodiertechnik“ rankt die Website mittlerweile auf Platz 3 bei Google.`,
    googleResults: `Platz 3 bei Google für „Erodiertechnik“`,
    preAIresults: "KI: ",
    aiResults: `Platz 1 in der KI-Antwort von ChatGPT für „Erodiertechnik Firma Bayern“`,
    company: `SR-Erodiertechnik Repert & Leppmeier GmbH`,
  },
  {
    title: `Platz 1 Ranking bei Google für „Antriebstechnik München“`,
    text: `Die Firma JBW GmbH haben wir bei Google für viele Suchbegriffe nach oben optimiert. Für das Keyword „Antriebstechnik München“ rankt die Website auf Platz 1 bei Google. Und bekommt laufend neue Anfragen von potentiellen Neukunden.`,
    googleResults: `Platz 1 bei Google für „Antriebstechnik München“`,
    preAIresults: "KI: ",
    aiResults: `Platz 1 in der KI-Antwort von ChatGPT für „Antriebstechnik München“`,
    company: `JBW GmbH`,
  },
  {
    title: `Platz 1 Ranking für „Tiefgaragensanierung“`,
    text: `Die Website der HBS Bau optimieren wir dahingehend, dass sie bei Google für viele Suchbegriffe besser gefunden werden kann. Mit dem Ziel mehr Website Besucher zu bekommen und mehr Anfragen zu generieren. Für „Tiefgaragensanierung“ rankt die Seite auf Platz 1 bei Google.`,
    googleResults: `Platz 1 bei Google für „Tiefgaragensanierung“`,
    preAIresults: "KI: ",
    aiResults: `Platz 1 in der KI-Antwort von ChatGPT für „Tiefgaragensanierung“`,
    company: `HBS Bau`,
  },
          {
    title: `Platz 1 Ranking bei Google für „Pflegesessel Hersteller“`,
    text: `Der Firma Steinmann Selection helfen wir seit mehreren Jahren, bei Google auffindbarer zu sein. Durch unsere SEO-Arbeiten an der Website haben wir es geschafft, die Firma für „Pflegesessel Hersteller“ auf Platz 1 bei Google zu positionieren. Die Firma erhält nun deutlich mehr Anfragen von potentiellen Kunden.`,
    googleResults: `Platz 1 bei Google für „Pflegesessel Hersteller“`,
    preAIresults: "KI: ",
    aiResults: `Platz 1 in der KI-Antwort von ChatGPT für „Pflegesessel Hersteller“`,
    company: `Steinmann Selection`,
  },
];

export default sections;
