import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import Footer from "./components/footer/Footer";
import PreFooter from "./components/footer/PreFooter";
import Navbar from "./components/navbar/Navbar";
import ScrollToTopBtn from "./components/ScrollToTopBtn";


const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter"
});

 const poppins = Poppins({
   variable: "--font-poppins",
   subsets: ["latin"],
   weight: ["400", "600", "700"],
   display: "swap",
 });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function MainLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${poppins.variable} antialiased`}
      >
        <Navbar/>
        {children}
        <Footer/>
        <ScrollToTopBtn/>
      </body>
    </html>
  );
}
