import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import "../globals.css";
import Navbar from "../components/navbar/Navbar";
import Footer from "../components/footer/Footer";
import PreFooter from "../components/footer/PreFooter";
import ScrollToTopBtn from "../components/ScrollToTopBtn";
import GTMBodyScript from "../components/google/GTMBodyScript";
import GTMHeadScript from "../components/google/GTMHeadScript";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "600", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function MainLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="de">
      <head>
        <GTMHeadScript/>
      </head>
      <body
        className={`${inter.variable} ${poppins.variable} antialiased`}
      >
        <GTMBodyScript/>
        <Navbar />
        <main>
          {children}
        </main>
        <PreFooter />
        <Footer />
        <ScrollToTopBtn />
      </body>
    </html>
  );
}
